

networks:
  grpc_network:
    driver: bridge

services:
  web:
    build:
      context: ./system1
      dockerfile: Dockerfile
    container_name: django-user-grpc
    # env_file:
    #   - ./system1/.env
    ports:
      - "8002:8000"
    depends_on:
      - db
      # - kong
    environment:
      - PORT=8002
    volumes:
      - ./system1:/app
      

  db:
    image: postgres:14
    container_name: postgres-user-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: grpc
      POSTGRES_PASSWORD: grpc@123
      POSTGRES_DB: grpc_user_DB
    ports:
      - "5432:5432"
  
  kong:
    image: kong
    container_name: kong-api-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - web


volumes:
  postgres_data: