# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\xaa\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\x11\n\tis_active\x18\x07 \x01(\x08\x12\x14\n\x0cis_superuser\x18\x08 \x01(\x08\x12\x10\n\x08is_staff\x18\t \x01(\x08\"p\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\"P\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x04user\x18\x03 \x01(\x0b\x32\n.user.User\"\x1f\n\x0eGetUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"+\n\x0fGetUserResposne\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x92\x01\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\x10\n\x08is_staff\x18\x07 \x01(\x08\x12\x14\n\x0cis_superuser\x18\x08 \x01(\x08\"P\n\x12UpdateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x04user\x18\x03 \x01(\x0b\x32\n.user.User\"\x13\n\x11GetAllUserRequest\"/\n\x12GetAllUserResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User2\x88\x02\n\x0bUserService\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResposne\x12?\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12?\n\nGetAllUser\x12\x17.user.GetAllUserRequest\x1a\x18.user.GetAllUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=21
  _globals['_USER']._serialized_end=191
  _globals['_CREATEUSERREQUEST']._serialized_start=193
  _globals['_CREATEUSERREQUEST']._serialized_end=305
  _globals['_CREATEUSERRESPONSE']._serialized_start=307
  _globals['_CREATEUSERRESPONSE']._serialized_end=387
  _globals['_GETUSERREQUEST']._serialized_start=389
  _globals['_GETUSERREQUEST']._serialized_end=420
  _globals['_GETUSERRESPOSNE']._serialized_start=422
  _globals['_GETUSERRESPOSNE']._serialized_end=465
  _globals['_UPDATEUSERREQUEST']._serialized_start=468
  _globals['_UPDATEUSERREQUEST']._serialized_end=614
  _globals['_UPDATEUSERRESPONSE']._serialized_start=616
  _globals['_UPDATEUSERRESPONSE']._serialized_end=696
  _globals['_GETALLUSERREQUEST']._serialized_start=698
  _globals['_GETALLUSERREQUEST']._serialized_end=717
  _globals['_GETALLUSERRESPONSE']._serialized_start=719
  _globals['_GETALLUSERRESPONSE']._serialized_end=766
  _globals['_USERSERVICE']._serialized_start=769
  _globals['_USERSERVICE']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
